[package]
name = "core-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
regex = "1.7.1"
syn   = {version = "1.0.107", features = ["full"]}
quote = "1.0.23"
